package com.sunrise.dental.service;

import com.sunrise.dental.dao.AppointmentDAO;
import com.sunrise.dental.dao.BillDAO;
import com.sunrise.dental.model.Appointment;
import com.sunrise.dental.model.Bill;
import com.sunrise.dental.strategy.BillingStrategy;
import com.sunrise.dental.strategy.StandardBillingStrategy;

/** Generates bills using only the price of the selected treatment. */
public class BillingService {
    private static final double NO_ADDITIONAL_CONSULTATION_FEE = 0.0;

    private final BillDAO billDAO;
    private final AppointmentDAO apptDAO;
    private final BillingStrategy strategy;

    public BillingService(BillDAO b, AppointmentDAO a) {
        billDAO = b;
        apptDAO = a;
        strategy = new StandardBillingStrategy();
    }

    public Bill generate(int appointmentId) {
        Appointment a = findAppointment(appointmentId);
        if (a == null || a.getTreatment() == null) {
            throw new IllegalArgumentException("Appointment or treatment not found");
        }

        double treatmentCost = Math.max(0.0, a.getTreatment().getBaseCost());
        double consultationFee = NO_ADDITIONAL_CONSULTATION_FEE;
        double discount = 0.0;

        Bill existing = billDAO.findByAppointment(appointmentId);
        if (existing != null) {
            // Repair older bills generated by the previous hard-coded Rs. 1,500 fee.
            existing.setConsultationFee(consultationFee);
            existing.setTreatmentCost(treatmentCost);
            existing.setDiscount(discount);
            existing.setTotalAmount(strategy.calculate(treatmentCost, consultationFee, discount));
            existing.setPricingStrategy(strategy.name());
            billDAO.update(existing);
            return existing;
        }

        Bill b = new Bill();
        b.setAppointmentId(appointmentId);
        b.setConsultationFee(consultationFee);
        b.setTreatmentCost(treatmentCost);
        b.setDiscount(discount);
        b.setTotalAmount(strategy.calculate(treatmentCost, consultationFee, discount));
        b.setPricingStrategy(strategy.name());
        int billId = billDAO.save(b);
        b.setBillId(billId);
        return b;
    }

    private Appointment findAppointment(int id) {
        for (Appointment a : apptDAO.findAll()) {
            if (a.getAppointmentId() == id) {
                return a;
            }
        }
        return null;
    }
}
