CREATE DATABASE IF NOT EXISTS sunrise_dental_clinic CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE sunrise_dental_clinic;
CREATE TABLE IF NOT EXISTS users(user_id INT AUTO_INCREMENT PRIMARY KEY,username VARCHAR(50) UNIQUE NOT NULL,password_hash VARCHAR(255) NOT NULL,role ENUM('ADMIN','STAFF') NOT NULL DEFAULT 'STAFF',full_name VARCHAR(100) NOT NULL,email VARCHAR(120),is_active BOOLEAN DEFAULT TRUE,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS patients(patient_id INT AUTO_INCREMENT PRIMARY KEY,appointment_number VARCHAR(30) UNIQUE NOT NULL,full_name VARCHAR(100) NOT NULL,address VARCHAR(255) NOT NULL,contact_number VARCHAR(20) NOT NULL,email VARCHAR(120),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,INDEX idx_patient_contact(contact_number));
CREATE TABLE IF NOT EXISTS dentists(dentist_id INT AUTO_INCREMENT PRIMARY KEY,full_name VARCHAR(100) NOT NULL,specialization VARCHAR(100) NOT NULL,contact_number VARCHAR(20),is_available BOOLEAN DEFAULT TRUE,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS treatments(treatment_id INT AUTO_INCREMENT PRIMARY KEY,treatment_name VARCHAR(100) UNIQUE NOT NULL,base_cost DECIMAL(10,2) NOT NULL,description VARCHAR(255),is_active BOOLEAN DEFAULT TRUE);
CREATE TABLE IF NOT EXISTS appointments(appointment_id INT AUTO_INCREMENT PRIMARY KEY,appointment_number VARCHAR(30) UNIQUE NOT NULL,patient_id INT NOT NULL,dentist_id INT NOT NULL,treatment_id INT NOT NULL,appointment_date DATE NOT NULL,appointment_time TIME NOT NULL,status ENUM('BOOKED','COMPLETED','CANCELLED') DEFAULT 'BOOKED',created_by INT,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(patient_id) REFERENCES patients(patient_id),FOREIGN KEY(dentist_id) REFERENCES dentists(dentist_id),FOREIGN KEY(treatment_id) REFERENCES treatments(treatment_id),FOREIGN KEY(created_by) REFERENCES users(user_id),INDEX idx_appt_datetime(dentist_id,appointment_date,appointment_time));
CREATE TABLE IF NOT EXISTS bills(bill_id INT AUTO_INCREMENT PRIMARY KEY,appointment_id INT UNIQUE NOT NULL,consultation_fee DECIMAL(10,2) NOT NULL,treatment_cost DECIMAL(10,2) NOT NULL,discount DECIMAL(10,2) DEFAULT 0,total_amount DECIMAL(10,2) NOT NULL,pricing_strategy VARCHAR(100),generated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(appointment_id) REFERENCES appointments(appointment_id));
CREATE TABLE IF NOT EXISTS system_logs(log_id INT AUTO_INCREMENT PRIMARY KEY,user_id INT,action VARCHAR(100) NOT NULL,details TEXT,ip_address VARCHAR(45),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(user_id) ON DELETE SET NULL);
INSERT IGNORE INTO users(username,password_hash,role,full_name,email) VALUES('admin', '$2a$10$04ulVLos1504cGNKpWA9seyZJb5ddSGdmRv7zCJ.8bsSSvDmVxGei','ADMIN','Clinic Administrator','admin@sunrisedental.lk');
-- Keep the demonstration login in sync with login.jsp even when the admin row already exists.
-- Demo credentials: admin / admin123
UPDATE users SET password_hash='$2a$10$04ulVLos1504cGNKpWA9seyZJb5ddSGdmRv7zCJ.8bsSSvDmVxGei' WHERE username='admin';
INSERT IGNORE INTO dentists(full_name,specialization,contact_number) VALUES('Dr. Amanda Perera','General Dentistry','0711111111'),('Dr. Kavindu Silva','Orthodontics','0722222222'),('Dr. Nethmi Fernando','Dental Surgery','0773333333');
INSERT IGNORE INTO treatments(treatment_name,base_cost,description) VALUES('Dental Consultation',1500,'Initial consultation'),('Dental Cleaning',3500,'Scaling and polishing'),('Filling',5000,'Composite filling'),('Root Canal',18000,'Root canal treatment'),('Tooth Extraction',7000,'Routine extraction'),('Teeth Whitening',12000,'Professional whitening');
DELIMITER //
DROP PROCEDURE IF EXISTS sp_create_appointment//
CREATE PROCEDURE sp_create_appointment(IN p_patient_name VARCHAR(100),IN p_address VARCHAR(255),IN p_contact VARCHAR(20),IN p_email VARCHAR(120),IN p_dentist_id INT,IN p_treatment_id INT,IN p_date DATE,IN p_time TIME,IN p_created_by INT,OUT p_appointment_number VARCHAR(30))
BEGIN DECLARE v_patient_id INT; DECLARE v_number VARCHAR(30); DECLARE v_count INT; SELECT COUNT(*) INTO v_count FROM appointments WHERE dentist_id=p_dentist_id AND appointment_date=p_date AND appointment_time=p_time AND status='BOOKED'; IF v_count>0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Dentist already has an appointment at this time'; END IF; SET v_number=CONCAT('APT-',DATE_FORMAT(NOW(),'%Y%m%d'),'-',LPAD(FLOOR(RAND()*100000),5,'0')); INSERT INTO patients(appointment_number,full_name,address,contact_number,email) VALUES(v_number,p_patient_name,p_address,p_contact,p_email); SET v_patient_id=LAST_INSERT_ID(); INSERT INTO appointments(appointment_number,patient_id,dentist_id,treatment_id,appointment_date,appointment_time,created_by) VALUES(v_number,v_patient_id,p_dentist_id,p_treatment_id,p_date,p_time,p_created_by); SET p_appointment_number=v_number; END//
DELIMITER ;
